name: post_to_websocket_broadcaster
description: A server application that listens for HTTP POST requests and broadcasts the body of the request to all connected websockets.
version: 1.0.0
repository: https://github.com/TechnicJelle/PostToWebsocketBroadcasterDart

environment:
  sdk: ^3.0.7

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_web_socket: ">=1.0.4 <3.0.0"
  web_socket_channel: ^2.4.0

dev_dependencies:
  http: ">=0.13.6 <2.0.0"
  lints: ">=2.0.0 <4.0.0"
  test: ^1.21.0
